### ISSUE TITLE
Problem with static content !

### ISSUE THREAD

**Issue by NoctisAtrae** [JoseRFelix/nextjs-starter-blog#11]
Hello 👋 !
I’m using your template and I have a problem : **I don’t understand how to use my assets**. When I write this in my markdown file : `![Test](thenameofthefile.jpg)`, Netlify cannot build my website whereas you can write `![cat](cat.jpeg)` and you get you image in the page. 

**Thanks !**

**Comment by JoseRFelix** [comment]
To load images, they have to be located in the `content/assets` folder. You can change this directory in the `MarkdownImage` component, inside `post/[slug].js` file.
