### ISSUE TITLE
Dark mode icon is sun on first load if system theme is dark

### ISSUE THREAD

**Issue by bhatsudo** [JoseRFelix/nextjs-starter-blog#17]
If the system theme is dark, and the website is loaded for the first time, the dark mode switch is still in sun mode even if the whole site is in dark mode.

It works fine after you switch to light mode and switch it back to dark mode.

It is also the same with your deployed application https://nextjs-starter-blog-demo.netlify.app/

Reproducible when you open the link in incognito mode.

**Comment by JoseRFelix** [comment]
Thanks for creating an issue! I'll fix it as soon as possible.

**Comment by bhatsudo** [comment]
> Thanks for creating an issue! I'll fix it as soon as possible.

Hello, thanks for the quick fix. But the fix leads to another bug. 

When you click the dark mode button now, the button itself disappears and cant switch anymore.
