### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by mrquincle** [JoseRFelix/nextjs-starter-blog#20]
Hi, what a lovely start for a blog. I run into an error though... I'm just cloning and running usual npm install and run stuff. 

![runtime_error](https://user-images.githubusercontent.com/1428585/101551516-64ea3f80-39b1-11eb-8326-554051a1bedc.png)

```
Unhandled Runtime Error
TypeError: parser is not a function
```

What am I doing wrong?

**Comment by mrquincle** [comment]
Never mind. Used yarn (and the lock file). It runs.

**Comment by JoseRFelix** [comment]
Awesome! Closing this.
