### ISSUE TITLE
Require in Runtime

### ISSUE THREAD

**Issue by pxwee5** [JoseRFelix/nextjs-starter-blog#4]
Specifically this line of code.
```
previewSrc={require(`../../content/assets/${src}?lqip`)}
```
All examples that I tried returns `Cannot find module`. What did you do here that made this work?

**Comment by JoseRFelix** [comment]
It depends where you putting your images and how you use them inside your markdown. 

On this setup, it should be inside the `content/assets` folder and in markdown just the name and the extension (e.g. cat.jpg).

You can change this easily by changing the path on that import. 

If you are following all these, then it could be related to a missing `lqip-loader`. I would love it if you could follow me up on this, so I can help you further.

**Comment by pxwee5** [comment]
Ah, thanks Jose. Found this. 
Also I realized that with this method, I have increased my page JS by 2-3 KB (gzip) per image. Offtopic but just wondering if you have the same issue as well.

**Comment by JoseRFelix** [comment]
This may be related `lazysizes` package which does allow for lazy loading images. I will be exploring possibilities such as this issue's comment: https://github.com/JoseRFelix/nextjs-starter-blog/issues/2#issuecomment-650576983. Regardless, performance should be carried out since 2kb and 3kb most likely won't affect much of it.

**Comment by pxwee5** [comment]
If the 3KB extra per image is `.jpg or .png`, then it won't affect performance.
Unfortunately, the 3KB extra is `.js`. Any extra kilobytes of javascript need to be parsed and evaluated by the browser, so that will definitely affect performance.

**Comment by JoseRFelix** [comment]
I know what you mean. JS can affect performance especially since the bundle size increases by image. I infer this javascript comes from the lazy loading functionality, which will increase the performance of the page even though extra js is added. Regardless, I'll be investigating this.
